In [1]:
import pandas as pd
df = pd.read_csv('novel-coronavirus - data_adm1.csv')
df

,country,location_id,location,latitude,longitude,confirmedcases_10-01-2020,deaths_10-01-2020,confirmedcases_11-01-2020,deaths_11-01-2020,confirmedcases_12-01-2020,...,confirmedcases_30-01-2020,deaths_30-01-2020,confirmedcases_31-01-2020,deaths_31-01-2020,confirmedcases_01-02-2020,deaths_01-02-2020,confirmedcases_02-02-2020,deaths_02-02-2020,confirmedcases_03-02-2020,deaths_03-02-2020
0,Australia,470,New South Wales,-32.3300,146.770,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0,4,0.0
1,Australia,476,Victoria,-36.9800,144.640,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,3.0,0.0,4.0,0.0,4.0,0.0,4,0.0
2,Australia,473,Queensland,-22.9000,144.700,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2,NaN
3,Australia,474,South Australia,-29.4900,135.950,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2,NaN
4,Cambodia,802,Sihanoukville,10.6160,103.578,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Vietnam,3347,Hanoi,21.1370,105.852,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2,NaN
82,Vietnam,3382,Thanh Hoa,20.0480,105.398,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1,NaN
83,Vietnam,3355,Khanh Hoa,12.2950,109.012,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1,NaN
84,Vietnam,3389,Vinh Phuc,21.3669,105.573,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
85,Germany,1314,Hessen,50.6640,9.085,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2,NaN

In [2]:
df = Out[1].copy()
import datetime as dt
dates = set([dt.date(int(col[-4:]),int(col[-7:-5]),int(col[-10:-8])) for col in df.columns if col.startswith(('confirmed','deaths'))])
dates = list(dates)
dates.sort()


# iterables = [dates,['confirmed_cases','deaths']]
# columns = pd.MultiIndex.from_product(iterables,names=['Date','Type'])
# df_new = pd.DataFrame(index=range(len(df.index)),columns=columns)

values = {}
for date in dates:
    datetext = date.strftime('%d-%m-%Y')
    values[date] = {'confirmed_cases':df[f'confirmedcases_{datetext}'].values,'deaths':df[f'deaths_{datetext}'].values}

df_new = pd.DataFrame().from_dict(values,'index')
series = df_new.stack()
df2 = pd.DataFrame(series)
df2 = df2

pd.DataFrame(df2[0].tolist(),index=df2.index).transpose()

        2020-01-10             2020-01-11             2020-01-12         \
   confirmed_cases deaths confirmed_cases deaths confirmed_cases deaths
0              0.0    0.0             0.0    0.0             0.0    0.0
1              0.0    0.0             0.0    0.0             0.0    0.0
2              NaN    NaN             NaN    NaN             NaN    NaN
3              NaN    NaN             NaN    NaN             NaN    NaN
4              0.0    0.0             0.0    0.0             0.0    0.0
..             ...    ...             ...    ...             ...    ...
81             NaN    NaN             NaN    NaN             NaN    NaN
82             NaN    NaN             NaN    NaN             NaN    NaN
83             NaN    NaN             NaN    NaN             NaN    NaN
84             NaN    NaN             NaN    NaN             NaN    NaN
85             NaN    NaN             NaN    NaN             NaN    NaN

        2020-01-13             2020-01-14         ...      2020-01-30         \
   confirmed_cases deaths confirmed_cases deaths  ... confirmed_cases deaths
0              0.0    0.0             0.0    0.0  ...             4.0    0.0
1              0.0    0.0             0.0    0.0  ...             3.0    0.0
2              NaN    NaN             NaN    NaN  ...             2.0    NaN
3              NaN    NaN             NaN    NaN  ...             NaN    NaN
4              0.0    0.0             0.0    0.0  ...             1.0    0.0
..             ...    ...             ...    ...  ...             ...    ...
81             NaN    NaN             NaN    NaN  ...             2.0    NaN
82             NaN    NaN             NaN    NaN  ...             1.0    NaN
83             NaN    NaN             NaN    NaN  ...             NaN    NaN
84             NaN    NaN             NaN    NaN  ...             NaN    NaN
85             NaN    NaN             NaN    NaN  ...             NaN    NaN

        2020-01-31             2020-02-01             2020-02-02         \
   confirmed_cases deaths confirmed_cases deaths confirmed_cases deaths
0              4.0    0.0             4.0    0.0             4.0    0.0
1              3.0    0.0             4.0    0.0             4.0    0.0
2              2.0    NaN             2.0    NaN             2.0    NaN
3              NaN    NaN             2.0    NaN             2.0    NaN
4              1.0    0.0             1.0    0.0             1.0    0.0
..             ...    ...             ...    ...             ...    ...
81             2.0    NaN             2.0    NaN             2.0    NaN
82             1.0    NaN             1.0    NaN             1.0    NaN
83             NaN    NaN             1.0    NaN             1.0    NaN
84             NaN    NaN             NaN    NaN             NaN    NaN
85             NaN    NaN             NaN    NaN             2.0    NaN

        2020-02-03
   confirmed_cases deaths
0              4.0    0.0
1              4.0    0.0
2              2.0    NaN
3              2.0    NaN
4              1.0    0.0
..             ...    ...
81             2.0    NaN
82             1.0    NaN
83             1.0    NaN
84             1.0    NaN
85             2.0    NaN

[86 rows x 50 columns]

In [22]:
df1 = Out[1].iloc[:,0:5]
df2 = Out[2]
df = pd.concat([df1,df2],axis=1,join='inner')
df
df.set_index(['country','location_id','location','latitude','longitude'],inplace=True)
df.columns = pd.MultiIndex.from_tuples(df.columns)
df

               confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               0.0
          476         Victoria        -36.9800 144.640               0.0
          473         Queensland      -22.9000 144.700               NaN
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               0.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               NaN
          3382        Thanh Hoa        20.0480 105.398               NaN
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-01-11  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               0.0
          476         Victoria        -36.9800 144.640               0.0
          473         Queensland      -22.9000 144.700               NaN
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               0.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               NaN
          3382        Thanh Hoa        20.0480 105.398               NaN
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-01-12  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               0.0
          476         Victoria        -36.9800 144.640               0.0
          473         Queensland      -22.9000 144.700               NaN
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               0.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               NaN
          3382        Thanh Hoa        20.0480 105.398               NaN
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-01-13  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               0.0
          476         Victoria        -36.9800 144.640               0.0
          473         Queensland      -22.9000 144.700               NaN
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               0.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               NaN
          3382        Thanh Hoa        20.0480 105.398               NaN
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-01-14  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               0.0
          476         Victoria        -36.9800 144.640               0.0
          473         Queensland      -22.9000 144.700               NaN
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               0.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               NaN
          3382        Thanh Hoa        20.0480 105.398               NaN
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 ...  \
                                                         deaths  ...
country   location_id location        latitude longitude         ...
Australia 470         New South Wales -32.3300 146.770      0.0  ...
          476         Victoria        -36.9800 144.640      0.0  ...
          473         Queensland      -22.9000 144.700      NaN  ...
          474         South Australia -29.4900 135.950      NaN  ...
Cambodia  802         Sihanoukville    10.6160 103.578      0.0  ...
...                                                         ...  ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN  ...
          3382        Thanh Hoa        20.0480 105.398      NaN  ...
          3355        Khanh Hoa        12.2950 109.012      NaN  ...
          3389        Vinh Phuc        21.3669 105.573      NaN  ...
Germany   1314        Hessen           50.6640 9.085        NaN  ...

                                                              2020-01-30  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               4.0
          476         Victoria        -36.9800 144.640               3.0
          473         Queensland      -22.9000 144.700               2.0
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               1.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               2.0
          3382        Thanh Hoa        20.0480 105.398               1.0
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-01-31  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               4.0
          476         Victoria        -36.9800 144.640               3.0
          473         Queensland      -22.9000 144.700               2.0
          474         South Australia -29.4900 135.950               NaN
Cambodia  802         Sihanoukville    10.6160 103.578               1.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               2.0
          3382        Thanh Hoa        20.0480 105.398               1.0
          3355        Khanh Hoa        12.2950 109.012               NaN
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-02-01  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               4.0
          476         Victoria        -36.9800 144.640               4.0
          473         Queensland      -22.9000 144.700               2.0
          474         South Australia -29.4900 135.950               2.0
Cambodia  802         Sihanoukville    10.6160 103.578               1.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               2.0
          3382        Thanh Hoa        20.0480 105.398               1.0
          3355        Khanh Hoa        12.2950 109.012               1.0
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 NaN

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-02-02  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               4.0
          476         Victoria        -36.9800 144.640               4.0
          473         Queensland      -22.9000 144.700               2.0
          474         South Australia -29.4900 135.950               2.0
Cambodia  802         Sihanoukville    10.6160 103.578               1.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               2.0
          3382        Thanh Hoa        20.0480 105.398               1.0
          3355        Khanh Hoa        12.2950 109.012               1.0
          3389        Vinh Phuc        21.3669 105.573               NaN
Germany   1314        Hessen           50.6640 9.085                 2.0

                                                                 \
                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

                                                              2020-02-03  \
                                                         confirmed_cases
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770               4.0
          476         Victoria        -36.9800 144.640               4.0
          473         Queensland      -22.9000 144.700               2.0
          474         South Australia -29.4900 135.950               2.0
Cambodia  802         Sihanoukville    10.6160 103.578               1.0
...                                                                  ...
Vietnam   3347        Hanoi            21.1370 105.852               2.0
          3382        Thanh Hoa        20.0480 105.398               1.0
          3355        Khanh Hoa        12.2950 109.012               1.0
          3389        Vinh Phuc        21.3669 105.573               1.0
Germany   1314        Hessen           50.6640 9.085                 2.0


                                                         deaths
country   location_id location        latitude longitude
Australia 470         New South Wales -32.3300 146.770      0.0
          476         Victoria        -36.9800 144.640      0.0
          473         Queensland      -22.9000 144.700      NaN
          474         South Australia -29.4900 135.950      NaN
Cambodia  802         Sihanoukville    10.6160 103.578      0.0
...                                                         ...
Vietnam   3347        Hanoi            21.1370 105.852      NaN
          3382        Thanh Hoa        20.0480 105.398      NaN
          3355        Khanh Hoa        12.2950 109.012      NaN
          3389        Vinh Phuc        21.3669 105.573      NaN
Germany   1314        Hessen           50.6640 9.085        NaN

[86 rows x 50 columns]